@startuml





/' Objects '/

class ConsolePlatform {
	-m_windowShouldClose : bool
	+shouldClose() : bool
	+getDeltaTime() : float
	+initWindow(int w, int h, const char* title) : void
	+shutdownWindow() : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
