@startuml





/' Objects '/

class ConsoleInputSystem {
	+ConsoleInputSystem(std::istream& input)
	+getKeyDown(InputAction action) : bool
	+getKeyPressed(InputAction action) : bool
	-m_previousState : bool[]
	-m_input : std::istream&
	+mapKey(InputAction action, int key) : void
	-processCommand(const std::string& command) : void
	+update() : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
