@startuml





/' Objects '/

class Enemy {
	+Enemy()
	+Enemy(float x, float y)
	-m_hitBox : Rect
	-m_hitBox : Rect
	-m_hitBox : Rect
	-m_hitBox : Rect
	-m_lastPosition : Vec2
	+checkPlayerCollision(const Rect& hitbox) : bool
	+isDead() : bool {query}
	-m_isDead : bool
	-m_health : float
	-m_speed : float
	+draw(Renderer& renderer) : void {query}
	+takeDamage(float value) : void
	+update(float dt) : void
	+walkTo(const Vec2& direction) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
