@startuml





/' Objects '/

abstract class Entity {
	+Entity()
	+Entity(float x, float y)
	+Entity(const Entity& other)
	+Entity(Entity&& other)
	+~Entity()
	+operator=(const Entity& other) : Entity&
	#m_hitBox : Rect
	#m_hitBox : Rect
	#m_hitBox : Rect
	#m_hitBox : Rect
	#m_hitBox : Rect
	+getHitBox() : Rect& {query}
	#m_position : Vec2
	#m_position : Vec2
	#m_position : Vec2
	#m_position : Vec2
	+getPos() : Vec2& {query}
	+clampToWorld(const Rect& rect) : void
	+{abstract} draw(Renderer& renderer) : void {query}
	+setPos(float x, float y) : void
	+{abstract} update(float dt) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
