@startuml





/' Objects '/

class EventManager <template<typename TOut=void, typename ... Args>> {
	+EventManager()
	+~EventManager()
	-m_handlers : Handler<TOut, Args ...>*
	+Subscribe(std::function<TOut ( Args ... )> func) : std::size_t
	-m_capacity : std::size_t
	-m_nextId : std::size_t
	-m_size : std::size_t
	+Invoke(CallArgs&& ... args) : void
	+Unsubscribe(std::size_t id) : void
	-resize() : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
