@startuml





/' Objects '/

class GameWorld {
	+GameWorld()
	-m_worldBoundary : Rect
	-m_worldBoundary : Rect
	-m_worldBoundary : Rect
	-m_worldBoundary : Rect
	-m_worldBoundary : Rect
	+getWorldBoundary() : Rect& {query}
	+draw(Renderer& renderer) : void {query}
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
