@startuml





/' Objects '/

abstract class InputSystem {
	+~InputSystem()
	+{abstract} getKeyDown(InputAction action) : bool
	+{abstract} getKeyPressed(InputAction action) : bool
	#m_currentState : bool[]
	#m_pressedState : bool[]
	#m_keyMaps : int[]
	+{abstract} mapKey(InputAction action, int key) : void
	+{abstract} update() : void
}


enum InputAction {
	ActionCount
	MoveDown
	MoveLeft
	MoveRight
	MoveUp
	Shoot
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
