@startuml





/' Objects '/

class MainMenuScene {
	+MainMenuScene()
	+~MainMenuScene()
	-m_container : UIContainer
	-createLayout() : void
	+draw(Renderer& renderer) : void {query}
	+update(float dt) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
