@startuml





/' Objects '/

class RaylibInputSystem {
	-RaylibInputSystem()
	+{static} instance() : RaylibInputSystem&
	+getKeyDown(InputAction action) : bool
	+getKeyPressed(InputAction action) : bool
	+mapKey(InputAction action, int key) : void
	+update() : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
