@startuml





/' Objects '/

class Rect {
	+h : float
	+w : float
	+x : float
	+y : float
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
