@startuml





/' Objects '/

class SceneManager {
	+SceneManager()
	+~SceneManager()
	-m_currentScene : IScene*
	-{static} m_requestedSceneChange : static bool
	+draw(Renderer& renderer) : void {query}
	+setScene(SCENES scene) : void
	+update(float dt) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
