@startuml





/' Objects '/

abstract class IScene {
	+~IScene()
	+{abstract} draw(Renderer& renderer) : void {query}
	+{abstract} update(float dt) : void
}


enum SCENES {
	GAMEPLAY
	GAME_OVER
	MAIN_MENU
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
