@startuml





/' Objects '/

class Timer {
	+Timer()
	+isFinished() : bool {query}
	+isRunning() : bool {query}
	-m_finished : bool
	-m_running : bool
	-m_duration : float
	-m_elapsed : float
	+reset() : void
	+start(float duration) : void
	+update(float dt) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
