@startuml





/' Objects '/

class UIButton {
	+UIButton(Vec2 position, Vec2 size, Color_rgb color, const std::string& text)
	+UIButton(const UIButton& other)
	-m_onClickedEvent : EventManager<void>
	+ButtonClicked() : EventManager<void>&
	+operator=(const UIButton& other) : UIButton&
	-m_size : Vec2
	-m_text : std::string
	+TriggerClick() : void
	+draw(Renderer& renderer) : void {query}
	+setText(const char* newText) : void
	+update(float dt) : void
}





/' Inheritance relationships '/




/' Aggregation relationships '/





/' Nested objects '/



@enduml
