@startuml





/' Objects '/

class UIContainer {
	+UIContainer()
	+~UIContainer()
	-m_layoutDir : LayoutDirection
	-m_children : UIElement**
	-spacing : float
	-m_size : std::size_t
	-m_size : std::size_t
	-m_size : std::size_t
	+add(UIElement* child) : void
	+draw(Renderer& renderer) : void {query}
	+layout() : void
	+update(float dt) : void
}


enum LayoutDirection {
	Horizontal
	Vertical
}





/' Inheritance relationships '/




/' Aggregation relationships '/

UIContainer *-- LayoutDirection






/' Nested objects '/



@enduml
